require('dotenv').config()
const express = require('express')
const consign = require('consign')
const app = express()

consign({ cwd: 'src' })
    .then('middlewares/bodyParser.js')
    .then('middlewares/cors.js')
    .then('mock')
    .then('routes/token.js')
    .then('middlewares/auth.js')
    .then('routes')
    .then('core')
    .into(app)